name: testAndLint

on: 
  push

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: make install
      - run: make test
      - run: make lint